# fp=open('login.py','x')
# fp.close()

#  output : FileExistsError: [Errno 17] File exists: 'login.py'

fp=open('one1.txt','x')
fp.close()